server:
  port: 8080

management:
  endpoints:
    web:
      exposure: # 애플리케이션 모니터링을 위한 웹 엔드포인트 노출
        include: health,prometheus,metrics
          # 공개할 엔드포인트 지정 - prometheus가 수집하는 메트릭스, micrometer를 사용해서 수집하는 지표
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      kitchen:
        base-config: default

        failure-rate-threshold: 20 # 실패율 임계치
        slow-call-rate-threshold: 100 # 지연율 임계치
        slow-call-duration-threshold: 500 # 지연시간 임계치, 이 시간을 초과하면 지연 호출로 판단
        minimum-number-of-calls: 10 # circuitbreaker 가 실패율, 지연율을 계산하기 전에 필요한 최소 호출 수
        # 임계치를 넘으면 서킷 오픈

        wait-duration-in-open-state: 1000
        automatic-transition-from-open-to-half-open-enabled: false
        # 서킷 오픈 후 1000ms가 지나고 새로운 요청을 처음 시도 했을 때 서킷을 반오픈

        permitted-number-of-calls-in-half-open-state: 5
        # 서킷 반오픈 상태에서 오픈/클로즈할지 결정하기 위한 호출 수

  retry:
    instances:
      kitchen:
        max-attempts: 3 # 최대 재시도 횟수
        wait-duration: 5s # 재시도 간격, 얼마 간격으로 재시도할지

logging:
  level:
    org.springframework.web.reactive: debug